version: '3'
services:
  php:
    image: yiisoftware/yii2-php:8.1-fpm-latest-nginx
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '8088:80'